version: 1.0.{build}
image: Visual Studio 2019

environment:
  nodejs_version: '18.12.0'

install:
  - ps: Install-Product node $env:nodejs_version
  - node -v
  - npm -v
  - yarn install

build_script:
  - echo Build started
  - cd %APPVEYOR_BUILD_FOLDER%
  - yarn install
